# application-prod.yml

jwt:
  secret: ${JWT_SECRET}
spring:

  #이미지 파일 크기 지정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 이메일 발송시 사용하는 html 템플릿 설정
  ## thymeleaf default settings
  thymeleaf:
    prefix: classpath:/mail-templates/   # 이메일 템플릿이 위치할 경로. classpath:를 통해 src/main/resources/ 밑으로 설정되었다.
    suffix: .html # 템플릿 파일의 확장자
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    ## thymeleaf custom settings
    cache: false

  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${USERPASSWORD}


  jpa:
    defer-datasource-initialization: true
    hibernate:
      #ddl-auto: create
      ddl-auto: none
      #hbm2ddl:
      # import_files: classpath:db/data.sql # DB ?? ????? ??
      #import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      connection:
        charSet: UTF-8 # ??? ??

    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:/db/data.sql

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465

# admin ?? ??
AdminMail:
  id: ${AdminMail_ID}
  password: ${AdminMail_PASSWORD}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESSKEY}
      secretKey: ${AWS_SECRETKEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto-: false

